services:
  dkron:
    image: dkron/dkron:4.0.4
    container_name: dkron
    ports:
      - 8080:8080
    command: >
      agent
      --server
      --bootstrap-expect=1
      --node-name=node1
    networks:
      - dkron_net
    restart: unless-stopped

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.8.1
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy-nginx.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    ports:
      - 4180:4180
    networks:
      - dkron_net

  nginx:
    depends_on:
      - oauth2-proxy
    container_name: nginx
    image: nginx:1.27
    restart: unless-stopped
    ports:
      - 80:80
    hostname: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - dkron_net

networks:
  dkron_net:
